name: CI

permissions:
  contents: read

on: [pull_request, push]

jobs:
  build:
    name: ${{ matrix.task.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
        task:
          - name: Check format
            run: cargo fmt -- --check
            allow_failure: false
          - name: Clippy
            run: cargo clippy
            allow_failure: true
          - name: Test
            run: cargo test --all
            allow_failure: false
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: ${{ matrix.task.name }}
        run:|
          cd auctioning_platform
          ${{ matrix.task.run }}
        continue-on-error: ${{ matrix.task.allow_failure }}
