[package]
name = "auctions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
foundation = { version = "0.1.0", path = "../foundation" }

[dev-dependencies]
rstest = "0.15.0"
